---
title: "p8105_hw2_rr3423"
author: "Ragyie Rawal"
date: "10/6/2021"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
```


## PROBLEM 1 

Mr. Trash Wheel:

```{r mr_trash_wheel, message = FALSE, warning = FALSE}
# importing and cleaning excel file data for Mr. Trash Wheel dataset 
mr_trash_wheel_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "Mr. Trash Wheel",
             range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  filter(!str_detect(month, 'Total')) %>% 
  mutate(sports_balls = round(sports_balls))
```

Precipitation Data 2018: 

```{r precipitation_2018, message = FALSE, warning = FALSE}
# reading and cleaning precipitation data for 2018 
precipitation_2018_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "2018 Precipitation",
             range = "A1:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = "2018")
```

Precipitation Data 2019:

```{r precipitation_2019, message = FALSE, warning = FALSE}
# reading and cleaning precipitation data for 2019 
precipitation_2019_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "2019 Precipitation",
             range = "A1:B8") %>% 
  janitor::clean_names() %>% 
  mutate(year = "2019")
```

